swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Account API
      description: API for fetching a user accounts
      parameters:
        - in: query
          name: token
          description: token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Account informations retrieved Successfully
          schema:
            $ref: '#/definitions/AccountResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /accounts/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API for fetching a user transaction details
      parameters:
        - in: query
          name: id
          description: Account ID
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /accounts/transactions/{year}/{month}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API by date
      description: API for fetching a user transactions from specific date
      parameters:
        - in: query
          name: id
          description: Account ID
          required: true
          type: integer
        - in: query
          name: year
          description: year
          required: true
          type: integer
        - in: query
          name: month
          description: month
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /accounts/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API for fetching a user transaction details
      parameters:
        - in: query
          name: id
          description: Transaction ID
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API for updating a user transaction details
      parameters:
        - in: query
          name: id
          description: Transaction ID
          required: true
          type: integer
        - in: body
          name: body
          description: Update user transaction attributes
          schema:
            $ref: '#/definitions/UserTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:

  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name

  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  Account:
    properties:
      id:
        type: string

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  AccountResponse:
    type: object
    properties:
      body:
        type: array
        items:
          $ref: "#/definitions/AccountModel"
  AccountModel:
    type: object
    properties:
      id:
        type: string
      balance:
        type: integer
      name:
        type: string

  TransactionsResponse:
    type: array
    items:
      $ref: "#/definitions/TransactionsModel"
  TransactionsModel:
    type: object
    properties:
      id:
        type: string
      account:
        type: string
      date:
        type: string
      title:
        type: string
      description:
        type: object
        properties:
          type:
            type: string
          category:
            type: string
          note:
            type: string
      amount:
        type: integer

  TransactionResponse:
    type: object
    properties:
      body:
        type: object
        properties:
          id:
            type: string
          account:
            type: string
          date:
            type: string
          title:
            type: string
          description:
            type: object
            properties:
              type:
                type: string
              category:
                type: string
              note:
                type: string
          amount:
            type: integer

  UserProfile:
    type: object
    properties:
      userName:
        type: string

  UserAccount:
    type: object
    properties:
      id:
        type: string

  UserTransaction:
    type: object
    properties:
      id:
        type: string
      category:
        type: string
      note:
        type: string
